# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poczta_centrum.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QLabel, QVBoxLayout, QWidget, QMessageBox, QTextBrowser, QLineEdit
from data_base import Account
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium .webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
import pyautogui as gui
import sys

class GmailInfoWindow(QWidget):

    def __init__(self, link, login, password):
        super().__init__()
        layout = QVBoxLayout()
        self.text_browser = QTextBrowser()
        self.text_browser.setPlainText(self.show_account(link, login, password))
        layout.addWidget(self.text_browser)
        self.setLayout(layout)

    def show_account(self, link, login, password):
        if login != "login":
            return f"Link: {link}" + 2*"\n" + f"Login: {login}" + 2*"\n" + f"Hasło: {password}"
        else:
            return link

class ChangePasswordWindow(QWidget):

    def __init__(self):
        super().__init__()
        layout = QVBoxLayout()
        self.label_old_password = QLabel("Stare hasło")
        self.label_new_password = QLabel("Nowe hasło")
        self.old_password_edit = QLineEdit()
        # self.old_password_edit.setEchoMode(QLineEdit.Password)
        self.new_password_edit = QLineEdit()
        self.submit_button = QPushButton("Zatwierdź")
        self.submit_button.setObjectName("submit_button")
        layout.addWidget(self.label_old_password)
        layout.addWidget(self.old_password_edit)
        layout.addWidget(self.label_new_password)
        layout.addWidget(self.new_password_edit)
        layout.addWidget(self.submit_button)
        self.submit_button.clicked.connect(lambda: self.submit_password())
        self.setLayout(layout)
        

    def submit_password(self):
        account_2 = Account()
        if account_2.update_password(self.old_password_edit.text(), self.new_password_edit.text()):
            self.show_popup("Hasło zostało zmienione")
        else:
            self.show_popup("Stare hasło jest niepoprawne!" + "\n" + "Spróbuj jeszcze raz.")
            self.old_password_edit.setText("")
            self.new_password_edit.setText("")

    def show_popup(self, text):
        msg = QMessageBox()
        msg.setWindowTitle("Błąd")
        msg.setText(text)
        x = msg.exec_()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 842)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(85, 170, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 511, 351))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("poradnia.bmp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        account = Account()

        # PORADNIA POCZTA BUTTON

        self.button_poczta_poradnia = QtWidgets.QPushButton(self.groupBox_2)
        self.button_poczta_poradnia.setGeometry(QtCore.QRect(180, 40, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.button_poczta_poradnia.setFont(font)
        self.button_poczta_poradnia.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 0, 0);")
        self.button_poczta_poradnia.setObjectName("button_poczta_poradnia")
        self.button_poczta_poradnia.clicked.connect(lambda: self.login(account.get_link_by_name("poradnia_poczta"), account.get_login_by_name("poradnia_poczta"), account.get_password_by_name("poradnia_poczta"), "user", "pass"))

        # PORADNIA GMAIL BUTTON

        self.button_gmail_poradnia = QtWidgets.QPushButton(self.groupBox_2)
        self.button_gmail_poradnia.setGeometry(QtCore.QRect(180, 140, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_gmail_poradnia.setFont(font)
        self.button_gmail_poradnia.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 0, 0);")
        self.button_gmail_poradnia.setObjectName("button_gmail_poradnia")
        self.button_gmail_poradnia.clicked.connect(lambda: self.show_new_window(account.get_link_by_name("poradnia_gmail"), account.get_login_by_name("poradnia_gmail"), account.get_password_by_name("poradnia_gmail")))

        # PORADNIA EDP BUTTON

        self.button_edp_poradnia = QtWidgets.QPushButton(self.groupBox_2)
        self.button_edp_poradnia.setGeometry(QtCore.QRect(180, 240, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_edp_poradnia.setFont(font)
        self.button_edp_poradnia.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 0, 0);")
        self.button_edp_poradnia.setObjectName("button_edp_poradnia")      
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.zsot_pic = QtWidgets.QLabel(self.groupBox)
        self.zsot_pic.setGeometry(QtCore.QRect(10, 20, 511, 351))
        self.zsot_pic.setText("")
        self.zsot_pic.setPixmap(QtGui.QPixmap("zsot.bmp"))
        self.zsot_pic.setScaledContents(True)
        self.zsot_pic.setObjectName("zsot_pic")
        self.button_edp_poradnia.clicked.connect(lambda: self.login(account.get_link_by_name("poradnia_edp"), account.get_login_by_name("poradnia_edp"), account.get_password_by_name("poradnia_edp"), "uname", "pwd"))

        # ZSOT IDZIENNIK BUTTON

        self.button_dziennik_zsot = QtWidgets.QPushButton(self.groupBox)
        self.button_dziennik_zsot.setGeometry(QtCore.QRect(190, 40, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.button_dziennik_zsot.setFont(font)
        self.button_dziennik_zsot.setMouseTracking(False)
        self.button_dziennik_zsot.setAutoFillBackground(False)
        self.button_dziennik_zsot.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 0, 0);")
        self.button_dziennik_zsot.setObjectName("button_dziennik_zsot")
        self.button_dziennik_zsot.clicked.connect(lambda: self.login(account.get_link_by_name("zsot_idziennik"), account.get_login_by_name("zsot_idziennik"), account.get_password_by_name("zsot_idziennik"), "LoginName", "Password"))

        # ZSOT PANEL BUTTON

        self.button_panel_zsot = QtWidgets.QPushButton(self.groupBox)
        self.button_panel_zsot.setGeometry(QtCore.QRect(190, 140, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_panel_zsot.setFont(font)
        self.button_panel_zsot.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 0, 0);")
        self.button_panel_zsot.setObjectName("button_panel_zsot")
        self.button_panel_zsot.clicked.connect(lambda: self.login(account.get_link_by_name("zsot_panel"), account.get_login_by_name("zsot_panel"), account.get_password_by_name("zsot_panel")))

        # ZSOT POCZTA BUTTON

        self.button_poczta_zsot = QtWidgets.QPushButton(self.groupBox)
        self.button_poczta_zsot.setGeometry(QtCore.QRect(190, 240, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_poczta_zsot.setFont(font)
        self.button_poczta_zsot.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 0, 0);")
        self.button_poczta_zsot.setObjectName("button_poczta_zsot")

        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 511, 341))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("trojka.bmp"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.button_poczta_zsot.clicked.connect(lambda: self.login(account.get_link_by_name("zsot_poczta"), account.get_login_by_name("zsot_poczta"), account.get_password_by_name("zsot_poczta"), "_user", "_pass"))

        # PRZEDSZKOLE POCZTA BUTTON

        self.button_poczta_przedszkole = QtWidgets.QPushButton(self.groupBox_3)
        self.button_poczta_przedszkole.setGeometry(QtCore.QRect(190, 90, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_poczta_przedszkole.setFont(font)
        self.button_poczta_przedszkole.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 0, 0);")
        self.button_poczta_przedszkole.setObjectName("button_poczta_przedszkole")
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 511, 341))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("poczta.bmp"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.button_poczta_przedszkole.clicked.connect(lambda: self.login(account.get_link_by_name("przedszkole_poczta"), account.get_login_by_name("przedszkole_poczta"), account.get_password_by_name("przedszkole_poczta"), "user", "pass"))

        # ONET BUTTON

        self.button_onet = QtWidgets.QPushButton(self.groupBox_4)
        self.button_onet.setGeometry(QtCore.QRect(190, 90, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_onet.setFont(font)
        self.button_onet.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 0, 0);")
        self.button_onet.setObjectName("button_onet")
        self.button_onet.clicked.connect(lambda: self.login(account.get_link_by_name("onet"), account.get_login_by_name("onet"), account.get_password_by_name("onet")))

        # GMAIL BUTTON

        self.button_gmail = QtWidgets.QPushButton(self.groupBox_4)
        self.button_gmail.setGeometry(QtCore.QRect(190, 190, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_gmail.setFont(font)
        self.button_gmail.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 0, 0);")
        self.button_gmail.setObjectName("button_gmail")
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.button_gmail.clicked.connect(lambda: self.show_new_window(account.get_link_by_name("gmail_priv"), account.get_login_by_name("gmail_priv"), account.get_password_by_name("gmail_priv")))


        # MENUBAR

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 25))
        self.menubar.setObjectName("menubar")
        self.menu_advanced = QtWidgets.QMenu(self.menubar)
        self.menu_advanced.setObjectName("menu_advanced")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_log_info = QtWidgets.QAction(MainWindow)
        self.action_log_info.setObjectName("action_log_info")
        self.action_change_password = QtWidgets.QAction(MainWindow)
        self.action_change_password.setObjectName("action_change_password")

        self.menu_advanced.addAction(self.action_log_info)
        self.menu_advanced.addAction(self.action_change_password)

        self.menubar.addAction(self.menu_advanced.menuAction())

        self.action_log_info.triggered.connect(lambda: self.show_new_window(account.get_all_records()))
        self.action_change_password.triggered.connect(lambda: self.change_password())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "POCZTA CENTRUM"))
        self.groupBox_2.setTitle(_translate("MainWindow", "PORADNIA"))
        self.button_poczta_poradnia.setText(_translate("MainWindow", "POCZTA"))
        self.button_gmail_poradnia.setText(_translate("MainWindow", "GMAIL"))
        self.button_edp_poradnia.setText(_translate("MainWindow", "EDP"))
        self.groupBox.setTitle(_translate("MainWindow", "ZSOT"))
        self.button_dziennik_zsot.setText(_translate("MainWindow", "I-DZIENNIK"))
        self.button_panel_zsot.setText(_translate("MainWindow", "PANEL"))
        self.button_poczta_zsot.setText(_translate("MainWindow", "POCZTA"))
        self.groupBox_3.setTitle(_translate("MainWindow", "PRZEDSZKOLE"))
        self.button_poczta_przedszkole.setText(_translate("MainWindow", "POCZTA"))
        self.groupBox_4.setTitle(_translate("MainWindow", "PRYWATNE"))
        self.button_onet.setText(_translate("MainWindow", "ONET"))
        self.button_gmail.setText(_translate("MainWindow", "GMAIL"))
        self.menu_advanced.setTitle(_translate("MainWindow", "ZAAWANSOWANE"))
        self.action_log_info.setText(_translate("MainWindow", "LOGIN INFO"))
        self.action_change_password.setText(_translate("MainWindow", "ZMIEŃ HASŁO"))

    def login(self, link, login, password, login_box="login", password_box="password"):


        chrome_driver = "chromedriver.exe"
        driver = webdriver.Chrome(chrome_driver)
        driver.get(link)
        driver.maximize_window()
        if login == "nauczyciel":
            time.sleep(1)
            gui.write(login)
            time.sleep(1)
            gui.press("tab")
            time.sleep(1)
            gui.write(password)
            time.sleep(1)
            gui.press("enter")
        else:
            try:
                element = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.NAME, login_box)))
            except TimeoutException as e:
                print(e)
            except:
                print("Sth wrong")
            else:
                element.send_keys(login)

            try:
                element = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.NAME, password_box)))
            except TimeoutException as e:
                print(e)
            except:
                print("Sth wrong")
            else:
                element.send_keys(password)
                time.sleep(1)
                element.send_keys(Keys.ENTER)


    def show_new_window(self, link, login = "login", password = "password"):
        self.w = GmailInfoWindow(link, login, password)
        self.w.show()

    def change_password(self):
        self.w = ChangePasswordWindow()
        self.w.show()

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
